<nav class="navbar">
	<a href="index.php" class="logo"><img src="../images/logo.png" alt="logo"></a>
	<div class="nav-links">
	<ul>
		<li><a href="index.php">Home</a></li>
		<li><a href="jobs.php" >Jobs</a></li>
		<li><a href="about.php">About</a></li>
		<li><a href="login.html">login</a></li>
		<li><a href="apply.php">Apply</a></li>
		<li><a href="enhancements.html">Enhancements</a></li>
	</ul>
	</div>
</nav>